services:
  nextjs-web:
    container_name: nextjs-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NEXTJS_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: nextjs-db
